# Generated by Django 3.0.3 on 2020-02-22 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(max_length=255)),
                ('ISBN_num', models.CharField(max_length=13, unique=True)),
                ('publisher', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='books_images')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('description', models.TextField()),
                ('picture_1', models.ImageField(upload_to='goods_images')),
                ('picture_2', models.ImageField(blank=True, upload_to='goods_images')),
                ('status', models.IntegerField(choices=[(1, '上架中'), (2, '待处理'), (3, '已下架')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Book')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.BookType'),
        ),
    ]
