# Generated by Django 3.0.3 on 2020-04-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_book_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_status',
        ),
    ]
