# Generated by Django 3.0.3 on 2020-04-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_book_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_status',
            field=models.IntegerField(choices=[(1, '上架中'), (2, '待处理'), (3, '已下架')], default=2),
        ),
    ]
