# Generated by Django 3.0.3 on 2020-04-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_book_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sale_volume',
            field=models.IntegerField(default=0),
        ),
    ]
