# Generated by Django 3.0.3 on 2020-02-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecord',
            name='picture',
            field=models.ImageField(blank=True, upload_to='message_images'),
        ),
        migrations.AlterField(
            model_name='transrecord',
            name='goods',
            field=models.CharField(default='', max_length=255),
        ),
    ]
