# Generated by Django 3.0.3 on 2020-02-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20200219_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagerecord',
            name='from_id',
        ),
        migrations.RemoveField(
            model_name='messagerecord',
            name='to_id',
        ),
        migrations.AddField(
            model_name='messagerecord',
            name='from_name',
            field=models.CharField(default='lyg', max_length=20),
        ),
        migrations.AddField(
            model_name='messagerecord',
            name='good_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='messagerecord',
            name='to_name',
            field=models.CharField(default='lyg', max_length=20),
        ),
    ]
