# Generated by Django 3.0.3 on 2020-02-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('center', '0002_auto_20200228_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transrecord',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Book'),
        ),
    ]
