# Generated by Django 3.0.3 on 2020-02-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_auto_20200219_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagerecord',
            name='from_name',
        ),
        migrations.RemoveField(
            model_name='messagerecord',
            name='to_name',
        ),
        migrations.AddField(
            model_name='messagerecord',
            name='from_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagerecord',
            name='to_id',
            field=models.IntegerField(default=0),
        ),
    ]
