# Generated by Django 3.0.3 on 2020-03-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_auto_20200228_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.IntegerField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='account',
            name='school',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='school_num',
            field=models.IntegerField(default=0, max_length=7),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(1, '正常状态'), (2, '封禁中')], default=1),
        ),
    ]
