# Generated by Django 3.0.3 on 2020-02-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20200218_2251'),
        ('center', '0005_auto_20200220_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerecord',
            name='good_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods'),
        ),
    ]
