# Generated by Django 3.0.3 on 2020-03-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_auto_20200302_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='school_num',
            field=models.IntegerField(),
        ),
    ]
