# Generated by Django 3.0.3 on 2020-04-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0007_auto_20200305_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='school_num',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(1, '正常状态'), (2, '封禁中'), (3, '未激活')], default=1),
        ),
    ]
